apiVersion: v1
kind: Pod
metadata:
  name: django
  labels:
    function: app
    version: v1
spec:
  containers:
  - name: django
    image: ghcr.io/mitzijferrer/cis-92:milestone-5.0
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 1000m 
        memory: 1024Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 1000m 
        memory: 1024Mi
        ephemeral-storage: 10Mi
    envFrom:
    - configMapRef:
        name: django
    - secretRef:
        name: django
    volumeMounts:
      - name : db
        mountPath: /data
  volumes:
    - name: db
      persistentVolumeClaim:
        claimName: mysite-data
  securityContext:
    fsGroup: 1000
  